version: '3.5'

services:

  db:
    container_name: pg_container
    image: postgres:13.3-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:5.7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  rmq:
    image: rabbitmq:3.8-management
    container_name: rabbit
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 5672:5672
      - 15672:15672
    restart: "no"

  postgres:
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    networks:
      - local-keycloak

  keycloak:
    depends_on:
      - postgres
    container_name: local_keycloak
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: ${POSTGRESQL_DB}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASSWORD: ${POSTGRESQL_PASS}
    image: jboss/keycloak:13.0.0
    ports:
      - "8081:8080"
    restart: unless-stopped
    networks:
      - local-keycloak

networks:
  local-keycloak:

    # keycloak:
    #   image: jboss/keycloak:16.1.1
    #   container_name: keycloak
    #   depends_on:
    #     postgresql:
    #       condition: service_started
    #   environment:
    #     DB_ADDR: postgresql
    #     DB_DATABASE: avatar_keycloak
    #     DB_PASSWORD: 3a9nvtwtECayWhhWgdLtrdKMwAibwJ4ccMddjENjzEeUejum3tzWPzye3AguMbt
    #     DB_USER: platform
    #     DB_VENDOR: postgres
    #     KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json
    #     KEYCLOAK_PASSWORD: YiPqYq4iTqAbsqxJyYoFvfMTumfkcAmREXRXHJyWftrY7sgKUA3qnzs3afvVi7s
    #     KEYCLOAK_USER: platform
    #     PROXY_ADDRESS_FORWARDING: "true"
    #   restart: always
